# Generated by Django 4.2.11 on 2024-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching', models.CharField(max_length=200)),
                ('IT', models.CharField(max_length=200)),
                ('engineering', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('learning', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
                ('involvement', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='usermedia')),
            ],
        ),
    ]
