# Generated by Django 4.2.11 on 2024-04-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='link',
            new_name='linkedin',
        ),
    ]
