# Generated by Django 4.2.11 on 2024-04-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0002_rename_link_linkedin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='linkedin',
            new_name='link',
        ),
    ]
